name: handTrackingEnvironment
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9.12
  - pip
  - pytorch=1.11.0
  - torchvision=0.12.0
  - torchaudio=0.11.0
  - pytorch-cuda
  - pip:
    - mediapipe
    - tqdm
    - pyright
    - tensorflow<2.11
    - protobuf==3.20
    - joblib
    - mtcnn
    - opencv-python
    - scikit-learn==1.3.2
