device_frame_rate: 30
draw_gaze_cone: true
gaze_beginning_buffer: 1.0
gaze_lookaway_buffer: 1.0
gaze_negative_count_time: 30.0
gaze_positive_count_time: 30.0
gaze_window: 30.0
group_gaze_event: 15.0
individual_gaze_event: 30.0
leanout_time: 1.0
left_position: -400.0
middle_position: 400.0
mkv_file_path: D:/multimodality/Demo3-sub2.mkv
mkv_frame_rate: 30
playback_frame_rate: 10
playback_time: 60.0
pose_negative_event: 10.0
pose_positive_event: 10.0
pose_window: 30.0
posture_negative_count_time: 30.0
posture_positive_count_time: 30.0
running_alive: false
smooth_frame: 1
speaker: P2
update_check_interval: 15.0
